### ISSUE TITLE
Run time optimaztion, Round 1

### ISSUE THREAD

**Issue by Schoema3** [PupoSDC/HiPSmixer#15]
The first profiling of the run time shows that the 6 most time consuming functions are:
1.   31.24%      Solver_Laminar::calculateMaxCourantNumber()
2.   20.34%      Field_Scalar_1D::operator[](int) const
3.   11.59%      Hips_Eddy_Generator::randomEddySelector()
4.    7.86%      Field_Scalar_1D::calculateAvailableEnergy(unsigned long, unsigned long, unsigned long)
5.    7.86%      Field_Scalar_1D::operator-(double)
6.    7.27%      Point::operator-(Point const&)

- [x] @ 1. remove
- [x] @ 2. rewrite to default `[]` operator, do the boundary checks with `assert`
- [ ] @ 3. rewrite in anyDSL and C++ ?
- [ ] @ 4. rewrite in anyDSL?
- [x] @ 5. rewrite in anyDSL?
- [x] @ 6. rewrite in anyDSL?

**Comment by PupoSDC** [comment]
fixed performance issues on operator [] on field scalar 1D #17 adressed issues 1 and 2

**Comment by PupoSDC** [comment]
New optimization round must be done. All the target functions noted as problematic have been reworked.
